#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNUE_THACSY.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HNUE_THACSY")]
	public partial class ThacSyDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertNganh(Nganh instance);
    partial void UpdateNganh(Nganh instance);
    partial void DeleteNganh(Nganh instance);
    partial void InsertTuyensinh(Tuyensinh instance);
    partial void UpdateTuyensinh(Tuyensinh instance);
    partial void DeleteTuyensinh(Tuyensinh instance);
    partial void InsertTinh(Tinh instance);
    partial void UpdateTinh(Tinh instance);
    partial void DeleteTinh(Tinh instance);
    #endregion
		
		public ThacSyDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SiteSqlServer"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ThacSyDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThacSyDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThacSyDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThacSyDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Nganh> Nganhs
		{
			get
			{
				return this.GetTable<Nganh>();
			}
		}
		
		public System.Data.Linq.Table<Tuyensinh> Tuyensinhs
		{
			get
			{
				return this.GetTable<Tuyensinh>();
			}
		}
		
		public System.Data.Linq.Table<Tinh> Tinhs
		{
			get
			{
				return this.GetTable<Tinh>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nganh")]
	public partial class Nganh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Idnganh;
		
		private string _tennganh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdnganhChanging(int value);
    partial void OnIdnganhChanged();
    partial void OntennganhChanging(string value);
    partial void OntennganhChanged();
    #endregion
		
		public Nganh()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idnganh", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Idnganh
		{
			get
			{
				return this._Idnganh;
			}
			set
			{
				if ((this._Idnganh != value))
				{
					this.OnIdnganhChanging(value);
					this.SendPropertyChanging();
					this._Idnganh = value;
					this.SendPropertyChanged("Idnganh");
					this.OnIdnganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennganh", DbType="NVarChar(255)")]
		public string tennganh
		{
			get
			{
				return this._tennganh;
			}
			set
			{
				if ((this._tennganh != value))
				{
					this.OntennganhChanging(value);
					this.SendPropertyChanging();
					this._tennganh = value;
					this.SendPropertyChanged("tennganh");
					this.OntennganhChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tuyensinh")]
	public partial class Tuyensinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _hoten;
		
		private string _cmnd;
		
		private string _gioitinh;
		
		private System.Nullable<System.DateTime> _ngaysinh;
		
		private string _noisinh;
		
		private string _sdt;
		
		private string _email;
		
		private string _nganh;
		
		private string _diachilienhe;
		
		private string _mienthingoaingu;
		
		private string _doituonguutien;
		
		private System.Nullable<double> _tongtien;
		
		private string _phieudangkyduthi;
		
		private string _donxinduthi;
		
		private string _bangtotnghiep;
		
		private string _bangdiemdaihoc;
		
		private string _soyeulilich;
		
		private string _giaysuckhoe;
		
		private string _avatar;
		
		private string _giayuutien;
		
		private string _giaymienthingoaingu;
		
		private string _hopdonglaodong;
		
		private string _congvanduthi;
		
		private string _giaynoptien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OncmndChanging(string value);
    partial void OncmndChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OnngaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysinhChanged();
    partial void OnnoisinhChanging(string value);
    partial void OnnoisinhChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnnganhChanging(string value);
    partial void OnnganhChanged();
    partial void OndiachilienheChanging(string value);
    partial void OndiachilienheChanged();
    partial void OnmienthingoainguChanging(string value);
    partial void OnmienthingoainguChanged();
    partial void OndoituonguutienChanging(string value);
    partial void OndoituonguutienChanged();
    partial void OntongtienChanging(System.Nullable<double> value);
    partial void OntongtienChanged();
    partial void OnphieudangkyduthiChanging(string value);
    partial void OnphieudangkyduthiChanged();
    partial void OndonxinduthiChanging(string value);
    partial void OndonxinduthiChanged();
    partial void OnbangtotnghiepChanging(string value);
    partial void OnbangtotnghiepChanged();
    partial void OnbangdiemdaihocChanging(string value);
    partial void OnbangdiemdaihocChanged();
    partial void OnsoyeulilichChanging(string value);
    partial void OnsoyeulilichChanged();
    partial void OngiaysuckhoeChanging(string value);
    partial void OngiaysuckhoeChanged();
    partial void OnavatarChanging(string value);
    partial void OnavatarChanged();
    partial void OngiayuutienChanging(string value);
    partial void OngiayuutienChanged();
    partial void OngiaymienthingoainguChanging(string value);
    partial void OngiaymienthingoainguChanged();
    partial void OnhopdonglaodongChanging(string value);
    partial void OnhopdonglaodongChanged();
    partial void OncongvanduthiChanging(string value);
    partial void OncongvanduthiChanged();
    partial void OngiaynoptienChanging(string value);
    partial void OngiaynoptienChanged();
    #endregion
		
		public Tuyensinh()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(50)")]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmnd", DbType="NChar(20)")]
		public string cmnd
		{
			get
			{
				return this._cmnd;
			}
			set
			{
				if ((this._cmnd != value))
				{
					this.OncmndChanging(value);
					this.SendPropertyChanging();
					this._cmnd = value;
					this.SendPropertyChanged("cmnd");
					this.OncmndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(5)")]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noisinh", DbType="NVarChar(50)")]
		public string noisinh
		{
			get
			{
				return this._noisinh;
			}
			set
			{
				if ((this._noisinh != value))
				{
					this.OnnoisinhChanging(value);
					this.SendPropertyChanging();
					this._noisinh = value;
					this.SendPropertyChanged("noisinh");
					this.OnnoisinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="NChar(20)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NChar(30)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nganh", DbType="NVarChar(50)")]
		public string nganh
		{
			get
			{
				return this._nganh;
			}
			set
			{
				if ((this._nganh != value))
				{
					this.OnnganhChanging(value);
					this.SendPropertyChanging();
					this._nganh = value;
					this.SendPropertyChanged("nganh");
					this.OnnganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachilienhe", DbType="NVarChar(100)")]
		public string diachilienhe
		{
			get
			{
				return this._diachilienhe;
			}
			set
			{
				if ((this._diachilienhe != value))
				{
					this.OndiachilienheChanging(value);
					this.SendPropertyChanging();
					this._diachilienhe = value;
					this.SendPropertyChanged("diachilienhe");
					this.OndiachilienheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mienthingoaingu", DbType="NVarChar(50)")]
		public string mienthingoaingu
		{
			get
			{
				return this._mienthingoaingu;
			}
			set
			{
				if ((this._mienthingoaingu != value))
				{
					this.OnmienthingoainguChanging(value);
					this.SendPropertyChanging();
					this._mienthingoaingu = value;
					this.SendPropertyChanged("mienthingoaingu");
					this.OnmienthingoainguChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doituonguutien", DbType="NVarChar(50)")]
		public string doituonguutien
		{
			get
			{
				return this._doituonguutien;
			}
			set
			{
				if ((this._doituonguutien != value))
				{
					this.OndoituonguutienChanging(value);
					this.SendPropertyChanging();
					this._doituonguutien = value;
					this.SendPropertyChanged("doituonguutien");
					this.OndoituonguutienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongtien", DbType="Float")]
		public System.Nullable<double> tongtien
		{
			get
			{
				return this._tongtien;
			}
			set
			{
				if ((this._tongtien != value))
				{
					this.OntongtienChanging(value);
					this.SendPropertyChanging();
					this._tongtien = value;
					this.SendPropertyChanged("tongtien");
					this.OntongtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phieudangkyduthi", DbType="NChar(30)")]
		public string phieudangkyduthi
		{
			get
			{
				return this._phieudangkyduthi;
			}
			set
			{
				if ((this._phieudangkyduthi != value))
				{
					this.OnphieudangkyduthiChanging(value);
					this.SendPropertyChanging();
					this._phieudangkyduthi = value;
					this.SendPropertyChanged("phieudangkyduthi");
					this.OnphieudangkyduthiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donxinduthi", DbType="NChar(30)")]
		public string donxinduthi
		{
			get
			{
				return this._donxinduthi;
			}
			set
			{
				if ((this._donxinduthi != value))
				{
					this.OndonxinduthiChanging(value);
					this.SendPropertyChanging();
					this._donxinduthi = value;
					this.SendPropertyChanged("donxinduthi");
					this.OndonxinduthiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bangtotnghiep", DbType="NChar(30)")]
		public string bangtotnghiep
		{
			get
			{
				return this._bangtotnghiep;
			}
			set
			{
				if ((this._bangtotnghiep != value))
				{
					this.OnbangtotnghiepChanging(value);
					this.SendPropertyChanging();
					this._bangtotnghiep = value;
					this.SendPropertyChanged("bangtotnghiep");
					this.OnbangtotnghiepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bangdiemdaihoc", DbType="NChar(30)")]
		public string bangdiemdaihoc
		{
			get
			{
				return this._bangdiemdaihoc;
			}
			set
			{
				if ((this._bangdiemdaihoc != value))
				{
					this.OnbangdiemdaihocChanging(value);
					this.SendPropertyChanging();
					this._bangdiemdaihoc = value;
					this.SendPropertyChanged("bangdiemdaihoc");
					this.OnbangdiemdaihocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soyeulilich", DbType="NChar(30)")]
		public string soyeulilich
		{
			get
			{
				return this._soyeulilich;
			}
			set
			{
				if ((this._soyeulilich != value))
				{
					this.OnsoyeulilichChanging(value);
					this.SendPropertyChanging();
					this._soyeulilich = value;
					this.SendPropertyChanged("soyeulilich");
					this.OnsoyeulilichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaysuckhoe", DbType="NChar(30)")]
		public string giaysuckhoe
		{
			get
			{
				return this._giaysuckhoe;
			}
			set
			{
				if ((this._giaysuckhoe != value))
				{
					this.OngiaysuckhoeChanging(value);
					this.SendPropertyChanging();
					this._giaysuckhoe = value;
					this.SendPropertyChanged("giaysuckhoe");
					this.OngiaysuckhoeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avatar", DbType="NChar(30)")]
		public string avatar
		{
			get
			{
				return this._avatar;
			}
			set
			{
				if ((this._avatar != value))
				{
					this.OnavatarChanging(value);
					this.SendPropertyChanging();
					this._avatar = value;
					this.SendPropertyChanged("avatar");
					this.OnavatarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giayuutien", DbType="NChar(30)")]
		public string giayuutien
		{
			get
			{
				return this._giayuutien;
			}
			set
			{
				if ((this._giayuutien != value))
				{
					this.OngiayuutienChanging(value);
					this.SendPropertyChanging();
					this._giayuutien = value;
					this.SendPropertyChanged("giayuutien");
					this.OngiayuutienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaymienthingoaingu", DbType="NChar(30)")]
		public string giaymienthingoaingu
		{
			get
			{
				return this._giaymienthingoaingu;
			}
			set
			{
				if ((this._giaymienthingoaingu != value))
				{
					this.OngiaymienthingoainguChanging(value);
					this.SendPropertyChanging();
					this._giaymienthingoaingu = value;
					this.SendPropertyChanged("giaymienthingoaingu");
					this.OngiaymienthingoainguChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hopdonglaodong", DbType="NChar(30)")]
		public string hopdonglaodong
		{
			get
			{
				return this._hopdonglaodong;
			}
			set
			{
				if ((this._hopdonglaodong != value))
				{
					this.OnhopdonglaodongChanging(value);
					this.SendPropertyChanging();
					this._hopdonglaodong = value;
					this.SendPropertyChanged("hopdonglaodong");
					this.OnhopdonglaodongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_congvanduthi", DbType="NChar(30)")]
		public string congvanduthi
		{
			get
			{
				return this._congvanduthi;
			}
			set
			{
				if ((this._congvanduthi != value))
				{
					this.OncongvanduthiChanging(value);
					this.SendPropertyChanging();
					this._congvanduthi = value;
					this.SendPropertyChanged("congvanduthi");
					this.OncongvanduthiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaynoptien", DbType="NChar(30)")]
		public string giaynoptien
		{
			get
			{
				return this._giaynoptien;
			}
			set
			{
				if ((this._giaynoptien != value))
				{
					this.OngiaynoptienChanging(value);
					this.SendPropertyChanging();
					this._giaynoptien = value;
					this.SendPropertyChanged("giaynoptien");
					this.OngiaynoptienChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tinh")]
	public partial class Tinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Idtinh;
		
		private string _tentinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdtinhChanging(int value);
    partial void OnIdtinhChanged();
    partial void OntentinhChanging(string value);
    partial void OntentinhChanged();
    #endregion
		
		public Tinh()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idtinh", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Idtinh
		{
			get
			{
				return this._Idtinh;
			}
			set
			{
				if ((this._Idtinh != value))
				{
					this.OnIdtinhChanging(value);
					this.SendPropertyChanging();
					this._Idtinh = value;
					this.SendPropertyChanged("Idtinh");
					this.OnIdtinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tentinh", DbType="NVarChar(255)")]
		public string tentinh
		{
			get
			{
				return this._tentinh;
			}
			set
			{
				if ((this._tentinh != value))
				{
					this.OntentinhChanging(value);
					this.SendPropertyChanging();
					this._tentinh = value;
					this.SendPropertyChanged("tentinh");
					this.OntentinhChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
